<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<parent>
		<groupId>com.holon-platform.jpa</groupId>
		<artifactId>holon-datastore-jpa-root</artifactId>
		<version>10.0.0</version>
	</parent>

	<artifactId>holon-starter-jpa-eclipselink</artifactId>
	<packaging>jar</packaging>

	<name>${project.groupId}:${project.artifactId}</name>
	<description>Holon Spring Boot JPA starter using EclipseLink and HikariCP datasource</description>

	<url>https://holon-platform.com</url>

	<dependencies>

		<!-- Holon base Spring boot stater -->
		<dependency>
			<groupId>com.holon-platform.core</groupId>
			<artifactId>holon-starter</artifactId>
		</dependency>

		<!-- Holon JPA Datastore -->
		<dependency>
			<groupId>com.holon-platform.jpa</groupId>
			<artifactId>holon-datastore-jpa-spring-boot</artifactId>
		</dependency>

		<!-- HikariCP Datasource -->
		<dependency>
			<groupId>com.zaxxer</groupId>
			<artifactId>HikariCP</artifactId>
			<exclusions>
				<exclusion>
					<groupId>org.slf4j</groupId>
					<artifactId>slf4j-api</artifactId>
				</exclusion>
			</exclusions>
		</dependency>

		<!-- EclipseLink -->
		<dependency>
			<groupId>org.eclipse.persistence</groupId>
			<artifactId>org.eclipse.persistence.jpa</artifactId>
		</dependency>

	</dependencies>

</project>