/*
 * Copyright 2016-2017 Axioma srl.
 * 
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 * 
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */
package com.holonplatform.jpa.spring.internal;

import org.springframework.transaction.PlatformTransactionManager;
import org.springframework.transaction.support.TransactionTemplate;

import com.holonplatform.core.datastore.Datastore.OperationResult;
import com.holonplatform.core.datastore.DatastoreOperations.WriteOption;
import com.holonplatform.core.datastore.DataTarget;
import com.holonplatform.core.property.PropertyBox;
import com.holonplatform.datastore.jpa.internal.DefaultJpaDatastore;

/**
 * AOT-compatible extension of {@link DefaultJpaDatastore} that wraps all write operations in a Spring-managed
 * transaction using a directly-injected {@link PlatformTransactionManager}.
 *
 * <p>Replaces the ByteBuddy runtime proxy previously generated by {@code JpaDatastoreRegistrar}. Using
 * {@link TransactionTemplate} rather than {@code @Transactional} keeps multi-context deployments correct:
 * each datastore instance receives the matching {@link PlatformTransactionManager} for its data context at
 * registration time, avoiding {@code NoUniqueBeanDefinitionException} when multiple transaction managers are
 * present.</p>
 *
 * <p>If no transaction manager is injected (e.g. {@code transactional=false}), operations execute without an
 * explicit transaction boundary.</p>
 *
 * @since 10.0.0
 */
public class TransactionalJpaDatastore extends DefaultJpaDatastore {

	private static final long serialVersionUID = 1L;

	private PlatformTransactionManager transactionManager;

	/**
	 * Set the {@link PlatformTransactionManager} to use for write operations.
	 * @param transactionManager the transaction manager for this data context
	 */
	public void setTransactionManager(PlatformTransactionManager transactionManager) {
		this.transactionManager = transactionManager;
	}

	private <R> R tx(java.util.function.Supplier<R> op) {
		if (transactionManager == null) {
			return op.get();
		}
		return new TransactionTemplate(transactionManager).execute(status -> op.get());
	}

	@Override
	public PropertyBox refresh(DataTarget<?> target, PropertyBox propertyBox) {
		return tx(() -> super.refresh(target, propertyBox));
	}

	@Override
	public OperationResult insert(DataTarget<?> target, PropertyBox propertyBox, WriteOption... writeOptions) {
		return tx(() -> super.insert(target, propertyBox, writeOptions));
	}

	@Override
	public OperationResult update(DataTarget<?> target, PropertyBox propertyBox, WriteOption... writeOptions) {
		return tx(() -> super.update(target, propertyBox, writeOptions));
	}

	@Override
	public OperationResult save(DataTarget<?> target, PropertyBox propertyBox, WriteOption... writeOptions) {
		return tx(() -> super.save(target, propertyBox, writeOptions));
	}

	@Override
	public OperationResult delete(DataTarget<?> target, PropertyBox propertyBox, WriteOption... writeOptions) {
		return tx(() -> super.delete(target, propertyBox, writeOptions));
	}

}

